package meter

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/evcc-io/evcc/api"
)

func decoratePowerWall3(base *FleetAPI, meterEnergy func() (float64, error), battery func() (float64, error), batteryCapacity func() float64, batterySocLimiter func() (float64, float64), batteryPowerLimiter func() (float64, float64), batteryController func(api.BatteryMode) error) api.Meter {
	switch {
	case battery == nil && meterEnergy == nil:
		return base

	case battery == nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.MeterEnergy
		}{
			FleetAPI: base,
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController == nil && batteryPowerLimiter == nil && batterySocLimiter == nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController == nil && batteryPowerLimiter == nil && batterySocLimiter == nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController == nil && batteryPowerLimiter == nil && batterySocLimiter == nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController == nil && batteryPowerLimiter == nil && batterySocLimiter == nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController == nil && batteryPowerLimiter == nil && batterySocLimiter != nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatterySocLimiter
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController == nil && batteryPowerLimiter == nil && batterySocLimiter != nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatterySocLimiter
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController == nil && batteryPowerLimiter == nil && batterySocLimiter != nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
			api.BatterySocLimiter
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController == nil && batteryPowerLimiter == nil && batterySocLimiter != nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
			api.BatterySocLimiter
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController == nil && batteryPowerLimiter != nil && batterySocLimiter == nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryPowerLimiter
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController == nil && batteryPowerLimiter != nil && batterySocLimiter == nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryPowerLimiter
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController == nil && batteryPowerLimiter != nil && batterySocLimiter == nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
			api.BatteryPowerLimiter
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController == nil && batteryPowerLimiter != nil && batterySocLimiter == nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
			api.BatteryPowerLimiter
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController == nil && batteryPowerLimiter != nil && batterySocLimiter != nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryPowerLimiter
			api.BatterySocLimiter
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController == nil && batteryPowerLimiter != nil && batterySocLimiter != nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryPowerLimiter
			api.BatterySocLimiter
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController == nil && batteryPowerLimiter != nil && batterySocLimiter != nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
			api.BatteryPowerLimiter
			api.BatterySocLimiter
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController == nil && batteryPowerLimiter != nil && batterySocLimiter != nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
			api.BatteryPowerLimiter
			api.BatterySocLimiter
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController != nil && batteryPowerLimiter == nil && batterySocLimiter == nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryController
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController != nil && batteryPowerLimiter == nil && batterySocLimiter == nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryController
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController != nil && batteryPowerLimiter == nil && batterySocLimiter == nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
			api.BatteryController
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController != nil && batteryPowerLimiter == nil && batterySocLimiter == nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
			api.BatteryController
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController != nil && batteryPowerLimiter == nil && batterySocLimiter != nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryController
			api.BatterySocLimiter
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController != nil && batteryPowerLimiter == nil && batterySocLimiter != nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryController
			api.BatterySocLimiter
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController != nil && batteryPowerLimiter == nil && batterySocLimiter != nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
			api.BatteryController
			api.BatterySocLimiter
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController != nil && batteryPowerLimiter == nil && batterySocLimiter != nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
			api.BatteryController
			api.BatterySocLimiter
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController != nil && batteryPowerLimiter != nil && batterySocLimiter == nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryController
			api.BatteryPowerLimiter
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController != nil && batteryPowerLimiter != nil && batterySocLimiter == nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryController
			api.BatteryPowerLimiter
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController != nil && batteryPowerLimiter != nil && batterySocLimiter == nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
			api.BatteryController
			api.BatteryPowerLimiter
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController != nil && batteryPowerLimiter != nil && batterySocLimiter == nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
			api.BatteryController
			api.BatteryPowerLimiter
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController != nil && batteryPowerLimiter != nil && batterySocLimiter != nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryController
			api.BatteryPowerLimiter
			api.BatterySocLimiter
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController != nil && batteryPowerLimiter != nil && batterySocLimiter != nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryController
			api.BatteryPowerLimiter
			api.BatterySocLimiter
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController != nil && batteryPowerLimiter != nil && batterySocLimiter != nil && meterEnergy == nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
			api.BatteryController
			api.BatteryPowerLimiter
			api.BatterySocLimiter
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController != nil && batteryPowerLimiter != nil && batterySocLimiter != nil && meterEnergy != nil:
		return &struct {
			*FleetAPI
			api.Battery
			api.BatteryCapacity
			api.BatteryController
			api.BatteryPowerLimiter
			api.BatterySocLimiter
			api.MeterEnergy
		}{
			FleetAPI: base,
			Battery: &decoratePowerWall3BatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWall3BatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatteryController: &decoratePowerWall3BatteryControllerImpl{
				batteryController: batteryController,
			},
			BatteryPowerLimiter: &decoratePowerWall3BatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
			BatterySocLimiter: &decoratePowerWall3BatterySocLimiterImpl{
				batterySocLimiter: batterySocLimiter,
			},
			MeterEnergy: &decoratePowerWall3MeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}
	}

	return nil
}

type decoratePowerWall3BatteryImpl struct {
	battery func() (float64, error)
}

func (impl *decoratePowerWall3BatteryImpl) Soc() (float64, error) {
	return impl.battery()
}

type decoratePowerWall3BatteryCapacityImpl struct {
	batteryCapacity func() float64
}

func (impl *decoratePowerWall3BatteryCapacityImpl) Capacity() float64 {
	return impl.batteryCapacity()
}

type decoratePowerWall3BatteryControllerImpl struct {
	batteryController func(api.BatteryMode) error
}

func (impl *decoratePowerWall3BatteryControllerImpl) SetBatteryMode(p0 api.BatteryMode) error {
	return impl.batteryController(p0)
}

type decoratePowerWall3BatteryPowerLimiterImpl struct {
	batteryPowerLimiter func() (float64, float64)
}

func (impl *decoratePowerWall3BatteryPowerLimiterImpl) GetPowerLimits() (float64, float64) {
	return impl.batteryPowerLimiter()
}

type decoratePowerWall3BatterySocLimiterImpl struct {
	batterySocLimiter func() (float64, float64)
}

func (impl *decoratePowerWall3BatterySocLimiterImpl) GetSocLimits() (float64, float64) {
	return impl.batterySocLimiter()
}

type decoratePowerWall3MeterEnergyImpl struct {
	meterEnergy func() (float64, error)
}

func (impl *decoratePowerWall3MeterEnergyImpl) TotalEnergy() (float64, error) {
	return impl.meterEnergy()
}
